version: '3.3'

services:
  blog:
    image: ghost:5.75-alpine
    restart: always
    ports:
      - 5555:2368
    volumes:
      - ./content:/var/lib/ghost/content
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: database
      database__connection__user: root
      database__connection__password: password
      database__connection__database: ghost
      url: https://umahserver.my.id
      NODE_ENV: production

  database:
    image: mysql:8.0
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "7306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ghost
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 5580:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password
